/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lkz.mathheus.xyz;

import java.awt.Toolkit;

/**
 *
 * @author mathh
 */

public class CalculadoraLkz extends javax.swing.JFrame {

    double num1 = 0;  
    double num2 = 0;  
    double resultado;
    int Verifican1 = 0;
    int Verifican2 = 0;
    double contN1 = 0;
    int operador = -1;  
    /**
     * Creates new form CalculadoraLkz
     */
    public CalculadoraLkz() {
        initComponents();
        setIcon();
        
       
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btn0 = new javax.swing.JButton();
        bntP = new javax.swing.JButton();
        bntIgual = new javax.swing.JButton();
        bntMais = new javax.swing.JButton();
        bnt1 = new javax.swing.JButton();
        bnt2 = new javax.swing.JButton();
        bnt3 = new javax.swing.JButton();
        bntMenos = new javax.swing.JButton();
        bnt4 = new javax.swing.JButton();
        bnt7 = new javax.swing.JButton();
        bnt5 = new javax.swing.JButton();
        bnt6 = new javax.swing.JButton();
        bntMuti = new javax.swing.JButton();
        bnt8 = new javax.swing.JButton();
        bnt9 = new javax.swing.JButton();
        bntDiv = new javax.swing.JButton();
        bntClear = new javax.swing.JButton();
        bntSair = new javax.swing.JButton();
        bntSqrt = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setResizable(false);
        setSize(new java.awt.Dimension(322, 483));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn0.setText("0");
        btn0.setMaximumSize(new java.awt.Dimension(70, 70));
        btn0.setMinimumSize(new java.awt.Dimension(70, 70));
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        getContentPane().add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 394, 70, 70));

        bntP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntP.setText(".");
        bntP.setMaximumSize(new java.awt.Dimension(70, 70));
        bntP.setMinimumSize(new java.awt.Dimension(70, 70));
        bntP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPActionPerformed(evt);
            }
        });
        getContentPane().add(bntP, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 394, 70, 70));

        bntIgual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntIgual.setText("=");
        bntIgual.setMaximumSize(new java.awt.Dimension(70, 70));
        bntIgual.setMinimumSize(new java.awt.Dimension(70, 70));
        bntIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntIgualActionPerformed(evt);
            }
        });
        getContentPane().add(bntIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 394, 70, 70));

        bntMais.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntMais.setText("+");
        bntMais.setMaximumSize(new java.awt.Dimension(70, 70));
        bntMais.setMinimumSize(new java.awt.Dimension(70, 70));
        bntMais.setPreferredSize(new java.awt.Dimension(39, 23));
        bntMais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMaisActionPerformed(evt);
            }
        });
        getContentPane().add(bntMais, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 394, 70, 70));

        bnt1.setText("1");
        bnt1.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt1.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 318, 70, 70));

        bnt2.setText("2");
        bnt2.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt2.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 318, 70, 70));

        bnt3.setText("3");
        bnt3.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt3.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 318, 70, 70));

        bntMenos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntMenos.setText("-");
        bntMenos.setMaximumSize(new java.awt.Dimension(70, 70));
        bntMenos.setMinimumSize(new java.awt.Dimension(70, 70));
        bntMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMenosActionPerformed(evt);
            }
        });
        getContentPane().add(bntMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 318, 70, 70));

        bnt4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt4.setText("4");
        bnt4.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt4.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, 70, 70));

        bnt7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt7.setText("7");
        bnt7.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt7.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt7ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 166, 70, 70));

        bnt5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt5.setText("5");
        bnt5.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt5.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 242, 70, 70));

        bnt6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt6.setText("6");
        bnt6.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt6.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt6ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt6, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 242, 70, 70));

        bntMuti.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntMuti.setText("x");
        bntMuti.setMaximumSize(new java.awt.Dimension(70, 70));
        bntMuti.setMinimumSize(new java.awt.Dimension(70, 70));
        bntMuti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntMutiActionPerformed(evt);
            }
        });
        getContentPane().add(bntMuti, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 242, 70, 70));

        bnt8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt8.setText("8");
        bnt8.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt8.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt8ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 166, 70, 70));

        bnt9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bnt9.setText("9");
        bnt9.setMaximumSize(new java.awt.Dimension(70, 70));
        bnt9.setMinimumSize(new java.awt.Dimension(70, 70));
        bnt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt9ActionPerformed(evt);
            }
        });
        getContentPane().add(bnt9, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 166, 70, 70));

        bntDiv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntDiv.setText("÷");
        bntDiv.setMaximumSize(new java.awt.Dimension(70, 70));
        bntDiv.setMinimumSize(new java.awt.Dimension(70, 70));
        bntDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntDivActionPerformed(evt);
            }
        });
        getContentPane().add(bntDiv, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 166, 70, 70));

        bntClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntClear.setText("APAGAR");
        bntClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntClearActionPerformed(evt);
            }
        });
        getContentPane().add(bntClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 146, 70));

        bntSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntSair.setText("SAIR");
        bntSair.setMaximumSize(new java.awt.Dimension(70, 70));
        bntSair.setMinimumSize(new java.awt.Dimension(70, 70));
        bntSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSairActionPerformed(evt);
            }
        });
        getContentPane().add(bntSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 90, 70, 70));

        bntSqrt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bntSqrt.setText("√");
        bntSqrt.setMaximumSize(new java.awt.Dimension(70, 70));
        bntSqrt.setMinimumSize(new java.awt.Dimension(70, 70));
        bntSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSqrtActionPerformed(evt);
            }
        });
        getContentPane().add(bntSqrt, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 90, 70, 70));

        lblResultado.setBackground(new java.awt.Color(255, 255, 255));
        lblResultado.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(1, 1, 1));
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResultado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 302, 73));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Developed by mathheusbueno - www.mathheusbueno.xyz");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 312, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(btn0.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+btn0.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    
    }//GEN-LAST:event_btn0ActionPerformed

    private void bntMutiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMutiActionPerformed
        // TODO add your handling code here:
        operador = 3;
    }//GEN-LAST:event_bntMutiActionPerformed

    private void bntClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntClearActionPerformed
        // TODO add your handling code here:
        lblResultado.setText(""); 
        num1 = (double)0;  
        num2 = (double)0;  
        operador = -1;
    }//GEN-LAST:event_bntClearActionPerformed

    private void bntMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMenosActionPerformed
        // TODO add your handling code here:
        operador = 2;
    }//GEN-LAST:event_bntMenosActionPerformed

    private void bntIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntIgualActionPerformed
        // TODO add your handling code here:
      switch (operador){
          case 1:resultado = num1 + num2;
          lblResultado.setText(String.valueOf(resultado));
          break;
          case 2:resultado = num1 - num2;
          lblResultado.setText(String.valueOf(resultado));
          break;
          case 3:resultado = num1 * num2;
          lblResultado.setText(String.valueOf(resultado));
          break;
          case 4:resultado = num1 / num2;
          lblResultado.setText(String.valueOf(resultado));
          break;
          case 5:resultado = Math.sqrt((int)num1);
          lblResultado.setText(String.valueOf(resultado));
          break;
          
          
      }
      
    }//GEN-LAST:event_bntIgualActionPerformed

    private void bntMaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntMaisActionPerformed
        // TODO add your handling code here:
        operador = 1;
        //lblResultado.setText(num1+"+" );
    }//GEN-LAST:event_bntMaisActionPerformed

    private void bntDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntDivActionPerformed
        // TODO add your handling code here:
        operador = 4;
    }//GEN-LAST:event_bntDivActionPerformed

    private void bntSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSqrtActionPerformed
        // TODO add your handling code here:
        operador = 5;
    }//GEN-LAST:event_bntSqrtActionPerformed

    private void bntSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSairActionPerformed
                System.exit(0); 
    }//GEN-LAST:event_bntSairActionPerformed

    private void bnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt1ActionPerformed

        if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt1.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt1.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }  
    }//GEN-LAST:event_bnt1ActionPerformed

    private void bnt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt2ActionPerformed
        if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt2.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt2.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    }//GEN-LAST:event_bnt2ActionPerformed

    private void bnt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt3ActionPerformed
       if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt3.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt3.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
        
    }//GEN-LAST:event_bnt3ActionPerformed
    
    private void bnt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt4ActionPerformed
        if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt4.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt4.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    }//GEN-LAST:event_bnt4ActionPerformed

    private void bnt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt5ActionPerformed
       if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt5.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt5.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    }//GEN-LAST:event_bnt5ActionPerformed

    private void bnt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt6ActionPerformed
        if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt6.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt6.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    }//GEN-LAST:event_bnt6ActionPerformed

    private void bnt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt7ActionPerformed
        if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt7.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt7.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    }//GEN-LAST:event_bnt7ActionPerformed

    private void bnt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt8ActionPerformed
        if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt8.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt8.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    }//GEN-LAST:event_bnt8ActionPerformed

    private void bnt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt9ActionPerformed
        if ((operador != -1) & (num2 == 0)){  
            lblResultado.setText("");  
        }  
        if (lblResultado.getText().length() == 0){  
                lblResultado.setText(bnt9.getText());  
        }else{  
                lblResultado.setText(lblResultado.getText()+""+bnt9.getText());  
            }  
        if (operador == -1){  
                num1 = Double.parseDouble(lblResultado.getText());  
        }else{  
                num2 = Double.parseDouble(lblResultado.getText());  
            }
    }//GEN-LAST:event_bnt9ActionPerformed

    private void bntPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPActionPerformed
        if (lblResultado.getText().equals("0"))  {
            lblResultado.setText(".");
        }
        else{
            lblResultado.setText(lblResultado.getText()+""+bntP.getText());
        }  
                  
    }//GEN-LAST:event_bntPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLkz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLkz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLkz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraLkz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraLkz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt1;
    private javax.swing.JButton bnt2;
    private javax.swing.JButton bnt3;
    private javax.swing.JButton bnt4;
    private javax.swing.JButton bnt5;
    private javax.swing.JButton bnt6;
    private javax.swing.JButton bnt7;
    private javax.swing.JButton bnt8;
    private javax.swing.JButton bnt9;
    private javax.swing.JButton bntClear;
    private javax.swing.JButton bntDiv;
    private javax.swing.JButton bntIgual;
    private javax.swing.JButton bntMais;
    private javax.swing.JButton bntMenos;
    private javax.swing.JButton bntMuti;
    private javax.swing.JButton bntP;
    private javax.swing.JButton bntSair;
    private javax.swing.JButton bntSqrt;
    private javax.swing.JButton btn0;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblResultado;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icone.png")));
    }
}
